# docker compose up -d
services:
  mariadb:
    image: mariadb
    container_name: 'mariadb_otis'
    ports:
      - "3336:3306"
    shm_size: 128mb
    environment:
      MARIADB_ROOT_PASSWORD: otis
      MARIADB_DATABASE: otis
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    networks:
      - otis_go_net
networks:
  otis_go_net:
    driver: bridge
