micronaut:
  serde:
    jackson:
      parser-features:
  application:
    name: Otis API

# OpenAPI
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
    swagger-ui:
      paths: classpath:META-INF/swagger/views/swagger-ui
      mapping: /swagger-ui/**