name: Publish Docker Images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build on ${{ matrix.os }}
        run: ./gradlew optimizedDockerfile optimizedDockerfileNative optimizedBuildLayers optimizedBuildNativeLayersTask
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: backend/build

  dockerNative:
    runs-on: ubuntu-latest
    needs:
      - gradle
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: backend/build
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.HARBOR_REGISTRY }}/otis/otis-native
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Log in to OneLiteFeather Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: ${{ secrets.HARBOR_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./backend/build/docker/native-optimized
  docker:
    runs-on: ubuntu-latest
    needs:
      - gradle
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: backend/build
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.HARBOR_REGISTRY }}/otis/otis
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Log in to OneLiteFeather Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          registry: ${{ secrets.HARBOR_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./backend/build/docker/optimized